---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-deploy-haproxy deploy-haproxy
  - cd deploy-haproxy

install:
  - pip install molecule docker

script:
  - molecule lint
